# Generated by Django 3.2.12 on 2022-03-04 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('Phno', models.CharField(max_length=20)),
                ('reg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.reg')),
            ],
        ),
    ]
