# Generated by Django 3.2.12 on 2022-03-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('pword', models.CharField(max_length=100)),
                ('secret', models.CharField(max_length=100)),
            ],
        ),
    ]
